// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOOD1wk2UHMJ5mBj96fbQUCzzIgirNH_s',
    appId: '1:58175880900:web:4b4db8ba9e531382319391',
    messagingSenderId: '58175880900',
    projectId: 'fir-747ab',
    authDomain: 'fir-747ab.firebaseapp.com',
    storageBucket: 'fir-747ab.appspot.com',
    measurementId: 'G-N9K03JN9TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAZmsAeqJGX9JCFpKF5E4OSvMTB9C14M',
    appId: '1:58175880900:android:fc60e64492e1afad319391',
    messagingSenderId: '58175880900',
    projectId: 'fir-747ab',
    storageBucket: 'fir-747ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9gkTmqxsbdJsB6J6FMTD9vVCsexvTqg',
    appId: '1:58175880900:ios:258b0f468a8f9e36319391',
    messagingSenderId: '58175880900',
    projectId: 'fir-747ab',
    storageBucket: 'fir-747ab.appspot.com',
    iosBundleId: 'com.example.ggtAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9gkTmqxsbdJsB6J6FMTD9vVCsexvTqg',
    appId: '1:58175880900:ios:258b0f468a8f9e36319391',
    messagingSenderId: '58175880900',
    projectId: 'fir-747ab',
    storageBucket: 'fir-747ab.appspot.com',
    iosBundleId: 'com.example.ggtAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOOD1wk2UHMJ5mBj96fbQUCzzIgirNH_s',
    appId: '1:58175880900:web:aa7a18ee2083fc4f319391',
    messagingSenderId: '58175880900',
    projectId: 'fir-747ab',
    authDomain: 'fir-747ab.firebaseapp.com',
    storageBucket: 'fir-747ab.appspot.com',
    measurementId: 'G-L9EYRQ6LKQ',
  );

}